// Generated by CoffeeScript 1.3.1
(function() {
  var code, compiled, result;

  code = texas_script.parser.parse("animal <= {\n  eat food: <= [((\"Animal ate \" ++ food) print)]\n  sleep <= [(\"Animal sleeping\" print)]\n}\n\nsnake <= (animal clone with-properties:{\n  eat food: <= [((\"Snake ate \" ++ food) print)]\n  slither <= [(\"Snake slithering\" print)]\n})\n\n(snake eat food:\"mouse\")\n(snake sleep)\n(snake slither)\n\nsnake");

  console.log("code:", code);

  compiled = texas_script.compiler.compile(code);

  console.log("compiled:", compiled);

  result = eval(compiled);

  console.log("result:", result);

}).call(this);
