// Generated by CoffeeScript 1.3.1
(function() {
  var code, compiled;

  code = texas_script.parser.parse("animal = {\n  eat food: = [food]\n  sleep = [\"sleeping\"]\n}");

  console.log("code:", code);

  compiled = texas_script.compiler.compile(code);

  console.log("compiled:", compiled);

  eval(compiled);

  console.log(animal);

}).call(this);
